#!/usr/bin/env bash

# Usage:
#   VCF_FILENAME="/path/to/input.vcf.gz" ./validate_vcf.sh
#
# Example:
#   VCF_FILENAME="/data/sample.vcf.gz" ./validate_vcf.sh

LOG_DIR="validation_logs"
RUN_TIMESTAMP=$(date '+%Y%m%d_%H%M%S')
RUN_NAME="${VCF_FILENAME##*/}"
RUN_NAME="${RUN_NAME%.vcf.gz}"
mkdir -p "$LOG_DIR"

CHECK_LOG="${LOG_DIR}/${RUN_NAME}_validation_${RUN_TIMESTAMP}.log"
PYTHON_RESOURCE_LOG="${LOG_DIR}/${RUN_NAME}_python_resources_${RUN_TIMESTAMP}.txt"
REFERENCE_PREFIX="SAMN12920115"

# Save all subsequent stdout and stderr from the checks to the run log,
# while also displaying it in the terminal.
exec > >(tee -a "$CHECK_LOG") 2>&1

: "${VCF_FILENAME:?Set VCF_FILENAME to the input VCF path}"
echo "Validation started: $(date)"
echo "Input VCF: $VCF_FILENAME"
echo "Expected generated reference VCF: ${REFERENCE_PREFIX}.vcf.gz"
echo "Python resource measurements: $PYTHON_RESOURCE_LOG"
#conda init
source activate base 
conda activate malariagen

echo
echo "========== Generate VCF from SNP calls =========="
if /usr/bin/time -l -o "$PYTHON_RESOURCE_LOG" \
    python3 make_vcf_from_snp_calls.py "$VCF_FILENAME"; then
    echo "Python script completed successfully."
else
    status=$?
    echo "Python script failed with exit status $status."
    echo "See $PYTHON_RESOURCE_LOG for elapsed time, CPU time, and peak memory."
    exit "$status"
fi
echo "Python resource measurements (macOS /usr/bin/time -l):"
cat "$PYTHON_RESOURCE_LOG"

echo
echo "========== Remaining VCF validation checks =========="

# total number of unique positions, indicating that several sites have two or more alternate alleles
bcftools view -v snps ${VCF_FILENAME} | grep -v "^#" | cut -f2 | sort -u | wc -l # 22573911
bcftools view -v snps SAMN12920115.vcf.gz | grep -v "^#" | cut -f2 | sort -u | wc -l # 60973065

bcftools view -e 'F_PASS(GT="ref") == 1' ${VCF_FILENAME} -o ${VCF_FILENAME%.vcf.gz}_homozygous_removed.vcf.gz
bcftools view -e 'F_PASS(GT="ref") == 1' SAMN12920115.vcf.gz -o SAMN12920115_homozygous_removed.vcf.gz 

bcftools index ${VCF_FILENAME%.vcf.gz}_homozygous_removed.vcf.gz
bcftools index SAMN12920115_homozygous_removed.vcf.gz

bcftools sort -O z -o ${VCF_FILENAME%.vcf.gz}_homozygous_removed.sorted.vcf.gz ${VCF_FILENAME%.vcf.gz}_homozygous_removed.vcf.gz
bcftools sort -O z -o SAMN12920115_homozygous_removed.sorted.vcf.gz SAMN12920115_homozygous_removed.vcf.gz

bcftools index ${VCF_FILENAME%.vcf.gz}_homozygous_removed.sorted.vcf.gz
bcftools index SAMN12920115_homozygous_removed.sorted.vcf.gz

bcftools view -v snps SAMN12920115_homozygous_removed.sorted.vcf.gz | grep -v "^#" | cut -f2 | sort -u | wc -l # 29302809
bcftools view -v snps ${VCF_FILENAME%.vcf.gz}_homozygous_removed.sorted.vcf.gz | grep -v "^#" | cut -f2 | sort -u | wc -l # 22573911

bcftools isec -p compare_vcfs_full_ag3 SAMN12920115_homozygous_removed.sorted.vcf.gz ${VCF_FILENAME%.vcf.gz}_homozygous_removed.sorted.vcf.gz

wc -l compare_vcfs_full_ag3/0002.vcf # Intesecting records: 27028131 compare_vcfs_full_ag3/0002.vcf
wc -l compare_vcfs_full_ag3/0000.vcf # Records in first file only: 11872282 compare_vcfs_full_ag3/0000.vcf
wc -l compare_vcfs_full_ag3/0001.vcf # Records in second file only: 18 compare_vcfs_full_ag3/0001.vcf


bedtools intersect -u -a SAMN12920115_homozygous_removed.sorted.vcf.gz -b ${VCF_FILENAME%.vcf.gz}_homozygous_removed.sorted.vcf.gz | wc -l # 27028101

vcf-compare SAMN12920115_homozygous_removed.sorted.vcf.gz ${VCF_FILENAME%.vcf.gz}_homozygous_removed.sorted.vcf.gz

# This file was generated by vcf-compare.
# The command line was: vcf-compare(v0.1.14-12-gcdb80b8) SAMN12920115_homozygous_removed.sorted.vcf.gz test_vcf_all_pysam_homozygous_removed.sorted.vcf.gz
#
#VN 'Venn-Diagram Numbers'. Use `grep ^VN | cut -f 2-` to extract this part.
#VN The columns are: 
#VN        1  .. number of sites unique to this particular combination of files
#VN        2- .. combination of files and space-separated number, a fraction of sites in the file
# VN	11872252	SAMN12920115_homozygous_removed.sorted.vcf.gz (30.5%)
# VN	27028101	SAMN12920115_homozygous_removed.sorted.vcf.gz (69.5%)	test_vcf_all_pysam_homozygous_removed.sorted.vcf.gz (100.0%)
# #SN Summary Numbers. Use `grep ^SN | cut -f 2-` to extract this part.
# SN	Number of REF matches:	27028101
# SN	Number of ALT matches:	27028101
# SN	Number of REF mismatches:	0
# SN	Number of ALT mismatches:	0
# SN	Number of samples in GT comparison:	0

# **2. Extract plain position lists** from all three files you need (malariagen ALT set, reference ALT set, reference *all* positions regardless of genotype):

bcftools query -f '%POS\n' ${VCF_FILENAME%.vcf.gz}_homozygous_removed.sorted.vcf.gz | sort -n -u > ${VCF_FILENAME%.vcf.gz}_alt_pos_full.txt
bcftools query -f '%POS\n' SAMN12920115_homozygous_removed.sorted.vcf.gz | sort -n -u > reference_alt_pos_full.txt
bcftools query -f '%POS\n' SAMN12920115.vcf.gz | sort -n -u > reference_all_pos_full.txt
# **3. Isolate the "extra" ALT positions** (in malariagen's set, not in the reference's own ALT set):

comm -23 ${VCF_FILENAME%.vcf.gz}_alt_pos_full.txt reference_alt_pos_full.txt > extra_alt_pos_full.txt
wc -l extra_alt_pos_full.txt # 3828591

# **4. Split those into case 1 (absent from reference entirely) vs. case 2 (present in reference, just not as ALT):**

comm -23 extra_alt_pos_full.txt reference_all_pos_full.txt > case1_absent_from_reference.txt
comm -12 extra_alt_pos_full.txt reference_all_pos_full.txt > case2_present_as_nonalt.txt

wc -l case1_absent_from_reference.txt # 3828591
wc -l case2_present_as_nonalt.txt # 0 

# Sanity check: `case1` + `case2` counts should sum to exactly the `extra_alt_pos.txt` count — a clean partition. If they don't, something's off with the position lists themselves (e.g. duplicate/overlapping records) rather than the underlying question, worth checking first.

# **5. If `case2` is non-trivial**, pull out a handful of those exact positions from both VCFs side by side to eyeball:

head -20 case2_present_as_nonalt.txt | awk '{print "2R\t"$1}' > spot_check_regions.txt

bcftools view -R spot_check_regions.txt test_vcf_chrom_2R_site_mask_none.vcf.gz | grep -v "^##"
bcftools view -R spot_check_regions.txt SAMN12920115_2R.vcf.gz | grep -v "^##"


bcftools view -H SAMN12920115_homozygous_removed.sorted.vcf.gz | awk '{print $1}' | sort | uniq -c
bcftools view -H ${VCF_FILENAME%.vcf.gz}_homozygous_removed.sorted.vcf.gz | awk '{print $1}' | sort | uniq -c

# have to guess there are more variants than just SNPs in output VCF cos other variant types are included?

bcftools view SAMN12920115_homozygous_removed.sorted.vcf.gz | grep -v "^#" | cut -f2 | sort -u | wc -l # 29302809
bcftools view ${VCF_FILENAME%.vcf.gz}_homozygous_removed.sorted.vcf.gz | grep -v "^#" | cut -f2 | sort -u | wc -l # 22573911

bcftools stats SAMN12920115_homozygous_removed.sorted.vcf.gz > ref_bcftools_stats.txt
bcftools stats ${VCF_FILENAME%.vcf.gz}_homozygous_removed.sorted.vcf.gz > output_bcftools_stats.txt

bcftools view -v snps ${VCF_FILENAME%.vcf.gz}_homozygous_removed.sorted.vcf.gz  | grep -v "^#" | cut -f4,5 | sort | uniq -c | sort -k1rn
bcftools view -v snps SAMN12920115_homozygous_removed.sorted.vcf.gz   | grep -v "^#" | cut -f4,5 | sort | uniq -c | sort -k1rn